---
- name: '[Shell] Install ZSH and friends'
  become: True
  become_user: root
  package: name={{ item }}
  with_items:
    - git-core
    - powerline
    - zsh

- name: '[Shell] Update shell to ZSH'
  become: True
  become_user: root
  command: chsh -s /bin/zsh {{ user }} 

- name: '[Shell] Check for Oh-My-Zsh'
  stat: path=$HOME/.oh-my-zsh
  register: ohmyzsh

- name: '[Shell] Install Oh-My-Zsh'
  shell: bash -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: not ohmyzsh.stat.exists

# TODO: Check and clone other custom plugins:
#  origin  https://github.com/Aloxaf/fzf-tab (fetch)
#  origin  https://github.com/supercrabtree/k (fetch)
#  origin  https://github.com/MichaelAquilina/zsh-you-should-use.git (fetch)
#  origin  https://github.com/zsh-users/zsh-autosuggestions (fetch)
#  origin  https://github.com/zsh-users/zsh-syntax-highlighting.git (fetch)

# TODO: copy .zshrc config here

- name: '[Shell] Check for powerlevel10k'
  stat: path=/$HOME/.oh-my-zsh/custom/themes/powerlevel10k
  register: powerlevel10k

- name: '[Shell] Clone powerlevel10k'
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ lookup("env", "HOME") }}/.oh-my-zsh/custom/themes/powerlevel10k
  when: not powerlevel10k.stat.exists

# TODO: copy .p10k.zsh config here