# Configure ansible-related stuff
---
- name: "[Ansible] Overwrite .ansible-lint. Overwrite flag is: {{ ansible_lint_overwrite }}"
  ansible.builtin.copy:
    src: .ansible-lint
    dest: "{{ ansible_env.HOME }}/.ansible-lint"
    mode: '0644'
  when: ansible_lint_overwrite | bool