# Configure ansible-related stuff
---
- name: "[Config][Ansible] Configure .ansible-lint"
  vars:
    app: ansible-lint
    source_file: ansible-lint
    target_file: "{{ ansible_env.HOME }}/.ansible-lint"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml
