# Configure LazyGIT
# Source: https://github.com/jesseduffield/lazygit
- name: "[Config][Lazygit] Ensure lazygit config directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/lazygit"
    state: directory
    mode: '0755'

- name: "[Config][Lazygit] Configure config.yml"
  vars:
    app: lazygit
    source_file: lazygit.yml
    target_file: "{{ ansible_env.HOME }}/.config/lazygit/config.yml"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml
