# Configure LazyGIT
# Source: https://github.com/jesseduffield/lazygit
- name: "[Config][LazyGIT] Ensure lazygit config directory"
  file:
    path: "{{ ansible_env.HOME }}/.config/lazygit"
    state: directory

- name: "[Config][LazyGIT] Copy config"
  ansible.builtin.copy:
    src: "lazygit.yml"
    dest: "{{ ansible_env.HOME }}/.config/lazygit/config.yml"
    mode: '0644'
  when: lazygit_config_overwrite | bool