# Configure LunarVIM
# Source: https://github.com/LunarVim/LunarVim
---
- name: "[Config][LunarVIM] Configure config.lua"
  vars:
    app: lunarvim
    source_file: lvim-config.lua
    target_file: "{{ ansible_env.HOME }}/.config/lvim/config.lua"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml
