# Configure necessary software (mostly dotfiles)
# For setting backup/overwrite options see `vars/main.yml`
---
- name: "[Config] Create backup dir {{ dotfiles_backup_dir }}"
  file:
    path: "{{ dotfiles_backup_dir }}"
    state: directory

# Include override variables
- name: "[Config] Include ansible/vars/overrides.yml"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ playbook_dir }}/vars/overrides.yml"
      skip: true

- name: "[Config] Configure zsh"
  include_tasks: zsh.yml
  when: "'zsh' not in config_tasks_exclude"

- name: "[Config] Configure p10k"
  include_tasks: p10k.yml
  when: "'p10k' not in config_tasks_exclude"

- name: "[Config] Configure tmux"
  include_tasks: tmux.yml
  when: "'tmux' not in config_tasks_exclude"

- name: "[Config] Configure sdkman"
  include_tasks: sdkman.yml
  when: "'sdkman' not in config_tasks_exclude"

- name: "[Config] Configure git"
  include_tasks: git.yml
  when: "'git' not in config_tasks_exclude"

- name: "[Config] Configure lazygit"
  include_tasks: lazygit.yml
  when: "'lazygit' not in config_tasks_exclude"

- name: "[Config] Configure lunarvim"
  include_tasks: lunarvim.yml
  when: "'lunarvim' not in config_tasks_exclude"

- name: "[Config] Configure thefuck"
  include_tasks: thefuck.yml
  when: "'thefuck' not in config_tasks_exclude"

- name: "[Config] Configure ansible"
  include_tasks: ansible.yml
  when: "'ansible' not in config_tasks_exclude"
