# Configure .p10k.zsh
# Set backup/overwrite flags in `vars/main.yml`
---
- name: "[Config][p10k] Configure .p10k.zsh"
  vars:
    app: p10k
    source_file: p10k.zsh
    target_file: "{{ ansible_env.HOME }}/.p10k.zsh"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml
