# Configure SDKMan
---
- name: "[Config][SDKMAN] Configure sdkman.config"
  vars:
    app: SDKMAN
    source_file: sdkman.config
    target_file: "{{ sdkman_dir }}/etc/config"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml
