# TheFuck config
# For usage see README.md
#
# Source: https://github.com/nvbn/thefuck
- name: "[Config][TheFuck] Ensure thefuck config directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/thefuck"
    state: directory
    mode: '0755'

- name: "[Config][TheFuck] Configure settings.py"
  vars:
    app: TheFuck
    source_file: thefuck-settings.py
    target_file: "{{ ansible_env.HOME }}/.config/thefuck/settings.py"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml
