# TheFuck config
# For usage see README.md
#
# Source: https://github.com/nvbn/thefuck
- name: "[Config][TheFuck] Ensure thefuck config directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/thefuck"
    state: directory
    mode: '0755'

- name: "[Config][TheFuck] Copy config"
  ansible.builtin.copy:
    src: "thefuck-settings.py"
    dest: "{{ ansible_env.HOME }}/.config/thefuck/settings.py"
    mode: '0644'
  when: thefuck_config_overwrite | bool
