---
- name: "[Config][Tmux] Configure .tmux.conf"
  vars:
    app: Tmux
    source_file: tmux.conf
    target_file: "{{ ansible_env.HOME }}/.tmux.conf"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml

# TODO: Add changed_when/failed_when
- name: "[Config][Tmux] Install plugins" # noqa no-changed-when
  ansible.builtin.command: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"

# TODO: Add changed_when/failed_when
- name: "[Config][Tmux] Update plugins" # noqa no-changed-when
  ansible.builtin.command: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/update_plugins all"
