# Configure VIM
# Set global/specific backup/overwrite flags in `vars/main.yml`
---
- name: "[Config][vim] Check for .vimrc"
  stat:
    path: "{{ ansible_env.HOME }}/.vimrc"
  register: vimrc_config

- name: "[Config][vim] Backup .vimrc. Backup flag is: {{ vimrc_backup | default(dotfiles_backup) }}"
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.vimrc"
    dest: "{{ dotfiles_backup_dir }}/.vimrc-{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
    remote_src: yes
  when: vimrc_config.stat.exists and vimrc_backup | default(dotfiles_backup) | bool

- name: "[Config][vim] Create VIM directories"
  file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: directory
  loop:
    - bundle
    - tmp
    - backup
    - colors

- name: "[Config][vim] Copy colorscheme"
  ansible.builtin.copy:
    src: bugi.vim
    dest: "{{ ansible_env.HOME }}/.vim/colors/bugi.vim"
    mode: '0644'

- name: "[Config][vim] Overwrite .vimrc. Overwrite flag is: {{ vimrc_overwrite | default(dotfiles_overwrite) }}"
  ansible.builtin.copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: '0644'
  when: vimrc_overwrite | default(dotfiles_overwrite) | bool