# Configure .zshrc
# Set backup/overwrite flags in `vars/main.yml`
---
- name: "[Config][ZSH] Get exact node version"
  ansible.builtin.shell: |
    set -e -o pipefail
    . {{ ansible_env.HOME }}/.local/opt/nvm/nvm.sh
    nvm use {{ node_version | default('default') }} 2>&1 1>/dev/null
    nvm list current | grep -Eo 'v[0-9]*\.[0-9]*\.[0-9]*'
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false
  register: actual_node_version

- name: "[Config][ZSH] Configure .zshrc"
  vars:
    app: ZSH
    source_template: zshrc.j2
    target_file: "{{ ansible_env.HOME }}/.zshrc"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml
