---
# LunarVIM
- name: "[LunarVIM] Install LunarVIM"
  shell: ". {{ ansible_env.HOME }}/.cargo/env; . {{ ansible_env.HOME }}/.local/opt/nvm/nvm.sh; dos2unix {{ lunarvim_home }}/utils/installer/install.sh; {{ lunarvim_home }}/utils/installer/install.sh -y"
  register: lunarvim_install
  notify: "[LunarVIM] Show LunarVIM install info"

- name: "[LunarVIM] Show LunarVIM install info"
  debug:
    msg: "{{ lunarvim_install.stdout | default('No output was passed from LunarVIM install command') }}"