---
# RVM / Ruby
rvm1_ansible_role_version: 2.2.0 # Version of https://github.com/rvm/rvm1-ansible 
rvm1_rubies:
  - ruby-2.4.10
  - ruby-2.7.6
  - ruby-3.1.2
rvm1_user: "{{ ansible_user_id }}"

# Puppet
puppet_version: 5.5.22 # Very old, but we still use it... Does not support `latest`, see https://rubygems.org/gems/puppet for latest version
puppet_rubies:
  - all # to install only for specific rubies, list their names (must match `rvm1_rubies`)
# Example:
#puppet_rubies:
#  - ruby-2.7.6
#  - ruby-3.1.2

# PDK (Puppet Development KIT)
# Please note the module does not support package downgrades - if PDK is already installed in higher version, remove it first.
pdk_version: latest

# NVM (Node Version Manager)
nvm_version: latest
node_version: 'lts/gallium'

# Ansible
ansible_pip_version: latest
ansible_lint_pip_version: latest

# Neovim
neovim_version: latest

# LunarVIM
lunarvim_url: https://github.com/lunarvim/lunarvim.git
lunarvim_home: "{{ ansible_env.HOME }}/.local/opt/lunarvim"
lunarvim_version: master

# Puppet
puppet_pes_url: https://github.com/puppetlabs/puppet-editor-services.git