# Install LunarVIM overlay/bundle for Neovim
# Source: https://github.com/LunarVim/LunarVim
---
- name: "[LunarVIM] Clone/update latest version"
  git:
    repo: "{{ lunarvim_url }}"
    dest: "{{ lunarvim_home }}"
    update: yes
    version: "{{ lunarvim_version }}"
  notify:
    - "[LunarVIM] Get NPM version string"
    - "[LunarVIM] Install LunarVIM"
    - "[LunarVIM] Show LunarVIM install info"

- name: "[LunarVIM] Ensure LunarVIM is really installed"
  shell: which lvim
  register: check_lvim
  changed_when: check_lvim.rc == 1
  failed_when: check_lvim.rc > 1
  notify:
    - "[LunarVIM] Get NPM version string"
    - "[LunarVIM] Install LunarVIM"
    - "[LunarVIM] Show LunarVIM install info"

- name: Flush handlers
  meta: flush_handlers

- name: "[LunarVIM] Update LunarVIM"
  shell: 'lvim +LvimUpdate +q'
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin/:{{ ansible_env.PATH }}"
  when: lunarvim_version in ['master', 'rolling']

- name: "[LunarVIM] Get installed version tag"
  shell: "git describe --tags | head -n 1 | awk -F'-' '{ print $1 }'"
  args:
    chdir: "{{ lunarvim_home }}"
  register: lunarvim_git_version

- name: "[LunarVIM] Save Lunarvim tag"
  set_fact:
    used_dev_versions: "{{ used_dev_versions | combine({'lunarvim_version': lunarvim_git_version.stdout}) }}"
