---
# Languages
- include_tasks: ansible.yml
- include_tasks: rvm.yml
- include_tasks: nvm.yml # Dependency for lvim.yml
- include_tasks: rust.yml # Dependency for lvim.yml
- include_tasks: neovim.yml
- include_tasks: lunarvim.yml
- include_tasks: puppet.yml