---
- name: '[Node] Install Node dependencies'
  become: true
  apt:
    name: "{{ node_dependencies }}"
  vars:
    node_dependencies:
      - dirmngr
      - gpg

- name: '[NVM/Node] Install Nodejs'
  shell: "asdf install nodejs {{ nodejs_version }}"

- name: '[NVM/Node] Set global Nodejs'
  shell: "asdf global nodejs {{ nodejs_version }}"
