# Install Puppet Development Kit
# Sources:
#   - https://github.com/puppetlabs/pdk
#   - https://puppet.com/docs/pdk/2.x/pdk.html
---

- name: "[PDK] Install repository sources"
  apt:
    deb: https://apt.puppet.com/puppet-tools-release-focal.deb
  become: True

- name: "[PDK] Install latest PDK"
  apt:
    name: pdk
    state: latest
    update_cache: yes
  become: True
  when: pdk_version == 'latest'

- name: "[PDK] Install PDK specific version"
  apt:
    name: "pdk={{ pdk_version }}"
    state: present
    update_cache: yes
  become: True
  when: pdk_version != 'latest'