---
- name: [Ruby] Install Ruby dependencies
  become: true
  apt:
    name: "{{ ruby_dependencies }}"
  vars:
    ruby_dependencies:
      - build-essential
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - automake

- name: [asdf/Ruby] Install Ruby
  shell: "asdf install ruby {{ ruby_version }}"

- name: [asdf/Ruby] Set global Ruby
  shell: "asdf global ruby {{ ruby_version }}"