---
# Overwrite below in `ansible/vars/overrides.yml` for your own info
git: # .gitconfig info
  name: Proveasio
  mail: Proveasio@hell.no

# Add this variable to your ansible/vars/overrides.yml if needed
# This is array of tasks to exclude from config role.
# For list of tasks see: config/tasks/main.yml or see README.md
config_tasks_exclude: []

# Path where to save configuration files
config_backup_dir: "{{ ansible_env.HOME }}/.configs_backup"

# Switch all config overwrites on/off
config_files_overwrite: true

# Backup config files on every
config_files_backup: true
