---
# TODO: update list of languages (+versions)
languages:
  ruby:
    version: 2.6.3
  nodejs:
    version: 14.17.0
# TODO: update list of tools (+versions)
tools:
  helm: 3.5.4
  asdf: 0.8.0
  pulumi: 3.3.1
