---
# FZF
- name: "[FZF] Run install script"
  ansible.builtin.shell: "{{ fzf_home }}/install"

# SDKMan
- name: "[SDKMan] Cleanup SDKMAN script"
  ansible.builtin.file:
    path: "{{ sdkman_tmp_dir }}/sdkman_script"
    state: absent
