# AWS CLI interface
# Source: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
---
- name: "[AWS CLI] Download archive"
  ansible.builtin.get_url:
    url: "{{ awscli_url }}"
    dest: "/tmp/awscliv2.zip"
    force: true
    mode: '0644'

- name: "[AWS CLI] Create installation directory in {{ ansible_env.HOME }}/.local/opt"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/opt/awscli-install"
    state: directory
    mode: '0755'

- name: "[AWS CLI] Extract binary"
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "{{ ansible_env.HOME }}/.local/opt/awscli-install"

- name: "[AWS CLI] Install/update"
  ansible.builtin.shell: |
    set -e -o pipefail
    ./aws/install --bin-dir {{ ansible_env.HOME }}/.local/bin --install-dir {{ ansible_env.HOME }}/.local/opt/aws-cli --update
  register: aws_install
  changed_when: aws_install.stdout is not regex('^Found same AWS CLI version:')
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/.local/opt/awscli-install"

- name: "[AWS CLI] Show install/update info"
  ansible.builtin.debug:
    msg: "{{ aws_install.stdout | default('No output was passed from AWS install command') }}"

- name: "[AWS CLI] Remove AWS cli from pip"
  ansible.builtin.pip:
    name: awscli
    state: absent
    executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip3"
