---
# Diff so fancy installation
# For configuration/implementation, refer to `shell` role GIT configuration
#
# Source: https://github.com/so-fancy/diff-so-fancy
- name: "[Diff so fancy] Get Github URL for proper version"
  vars:
    app: diff_so_fancy
    repo: so-fancy/diff-so-fancy
    version_query: curl -s https://api.github.com/repos/so-fancy/diff-so-fancy/releases/latest | jq .name -r | cut -f2 -d'v'
    artifact_uri: v{{ diff_so_fancy_version }}/diff-so-fancy
  ansible.builtin.import_role:
    name: common
    tasks_from: github_version.yml
  tags:
    - versions

- name: "[Diff so fancy] Check if Diff-so-fancy {{ diff_so_fancy_version }} is installed"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/opt/diff-so-fancy-{{ diff_so_fancy_version }}"
  register: dsf_dir

- name: "Installation"
  when: not dsf_dir.stat.exists
  block:

    - name: "[Diff so fancy] Create directory in {{ ansible_env.HOME }}/.local/opt"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/opt/diff-so-fancy-{{ diff_so_fancy_version }}"
        state: directory
        mode: '0755'

    - name: "[Diff so fancy] Download Diff-so-fancy {{ diff_so_fancy_version }}"
      ansible.builtin.get_url:
        url: "{{ dsf_url }}"
        dest: "{{ ansible_env.HOME }}/.local/opt/diff-so-fancy-{{ diff_so_fancy_version }}/diff-so-fancy"
        mode: '0755'

- name: "[Diff so fancy] Link {{ diff_so_fancy_version }} binary"
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/opt/diff-so-fancy-{{ diff_so_fancy_version }}/diff-so-fancy"
    dest: "{{ ansible_env.HOME }}/.local/bin/diff-so-fancy"
    state: link
    force: true

- name: "[Diff so fancy] Save used version"
  vars:
    app: diff_so_fancy
    target_version:
      github_packages:
        diff_so_fancy: "{{ diff_so_fancy_version }}"
    query: ".github_packages.diff-so-fancy = \"{{ diff_so_fancy_version }}\""
  ansible.builtin.import_role:
    name: common
    tasks_from: save_version.yml
  tags:
    - versions
