# Git fuzzy installation
# For usage see README.md
#
# Source: https://github.com/bigH/git-fuzzy.git
---
- name: "[Git-fuzzy] Clone/update latest version"
  ansible.builtin.git:
    repo: "{{ git_fuzzy_url }}"
    dest: "{{ git_fuzzy_home }}"
    update: true
    version: "{{ git_fuzzy_branch }}"
