# Install specific GIT version
---
- name: "[Git] Add git-core/ppa repository"
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa

- name: "[Git] Install GIT {{ versions.git }}"
  become: true
  ansible.builtin.apt:
    name: "git"
    state: "{{ versions.git }}"
    update_cache: true

- name: "[Git] Get installed GIT version"
  ansible.builtin.shell: |
    set -e -o pipefail
    apt info git 2>/dev/null | grep Version | awk '{print $2}' | awk -F '~' '{print $1}'
  register: git_version
  args:
    executable: /bin/bash
  changed_when: false

- name: "[Git] Save used version"
  ansible.builtin.set_fact:
    used_software_versions: "{{ used_software_versions | combine({'git': git_version.stdout}) }}"
