---
# Gita installation
# For usage see README.md
#
# Source: https://github.com/nosarthur/gita
- name: "[Gita] Install Gita specific version"
  pip:
    name: "gita=={{ versions.gita }}"
    executable: pip3
  register: pip_out
  changed_when: "'Requirement already up-to-date' not in pip_out.stdout"
  when: versions['gita'] != 'latest'

- name: "[Gita] Install Gita latest version"
  pip:
    name: "gita"
    executable: pip3
    extra_args: --upgrade
  register: pip_out
  changed_when: "'Requirement already up-to-date' not in pip_out.stdout"
  when: versions['gita'] == 'latest'