# Install LazyGIT
# Source: https://github.com/jesseduffield/lazygit
---
- name: "[LazyGIT] Add lazygit-team/release repository"
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:lazygit-team/release

- name: "[LazyGIT] Update OS packages list"
  become: true
  package:
    update_cache: yes

- name: "[LazyGIT] Install LazyGIT {{ versions.lazygit }}"
  become: true
  apt:
    name: "lazygit"
    state: "{{ versions.lazygit }}"

- name: "[LazyGIT] Get installed LazyGIT version"
  shell: "apt info lazygit 2>/dev/null | grep Version | awk '{print $2}' | awk -F '~' '{print $1}'"
  register: lazygit_version

- name: "[LazyGIT] Save used version"
  set_fact:
    used_software_versions: "{{ used_software_versions | combine({'lazygit': lazygit_version}) }}"