# ls-with-git-status
# Source: https://github.com/gerph/ls-with-git-status
---
- name: "[LSG] Copy ls-with-git-status binary"
  ansible.builtin.copy:
    src: "ls-with-git-status/lsg"
    dest: "{{ ansible_env.HOME }}/.local/bin/lsg"
    mode: '0755'