# Install LunarVIM overlay/bundle for Neovim
# Source: https://github.com/LunarVim/LunarVim
---
- name: "[LunarVIM] Get Github URL for proper version"
  vars:
    app: lunarvim
    repo: lunarvim/lunarvim
    version_query: curl -s https://api.github.com/repos/lunarvim/lunarvim/releases/latest | jq .name -r | cut -f2 -d'v'
  ansible.builtin.include_role:
    name: common
    tasks_from: github_version.yml
    apply:
      tags:
        - versions
  tags:
    - versions

- name: "[LunarVIM] Clone/update version {{ lunarvim_version }}"
  ansible.builtin.git:
    repo: "{{ lunarvim_url }}"
    dest: "{{ lunarvim_home }}"
    update: true
    version: "{{ lunarvim_version }}"
  notify:
    - "[LunarVIM] Get NPM version string"
    - "[LunarVIM] Install LunarVIM"
    - "[LunarVIM] Show LunarVIM install info"

- name: "[LunarVIM] Ensure LunarVIM is really installed"
  ansible.builtin.command: which lvim
  register: check_lvim
  changed_when: check_lvim.rc == 1
  failed_when: check_lvim.rc > 1
  notify:
    - "[LunarVIM] Get NPM version string"
    - "[LunarVIM] Install LunarVIM"
    - "[LunarVIM] Show LunarVIM install info"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: "[LunarVIM] Update LunarVIM"
  ansible.builtin.command: 'lvim +LvimUpdate +q'
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin/:{{ ansible_env.PATH }}"
  when: lunarvim_version in ['master', 'rolling']

- name: "[LunarVIM] Get version commit if version is master or rolling"
  ansible.builtin.shell: git rev-parse --short HEAD
  changed_when: false
  args:
    chdir: "{{ lunarvim_home }}"
    executable: /bin/bash
  register: lunarvim_git_version
  tags:
    - versions
  when: lunarvim_version in ['master', 'rolling']

- name: "[LunarVIM] Save used version"
  vars:
    app: lunarvim
    target_version:
      github_packages:
        lunarvim: "{{ lunarvim_git_version.stdout | default(lunarvim_version) }}"
    query: ".github_packages.lunarvim = \"{{ lunarvim_git_version.stdout | default(lunarvim_version) }}\""
  ansible.builtin.include_role:
    name: common
    tasks_from: save_version.yml
    apply:
      tags:
        - versions
  tags:
    - versions
