# NOTE: LunarVim is replaced by custom Neovim distribution (AstroNvim by default)
#
# Source: https://github.com/LunarVim/LunarVim
#
# If you want to completely remove LunarVim, see: https://www.lunarvim.org/docs/installation#uninstall
