---

# Ensure local bin/opt directories are there
- name: "[Software] Ensure dotted directories are there"
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - .local/bin
    - .local/opt
    - .config
    - .lsp

# Common software
- include_tasks: packages.yml

# ls-with-git-status
- include_tasks: lsg.yml

# FZF (fuzzy-finder)
- include_tasks: fzf.yml

# Diff-so-fancy
- include_tasks: diff-so-fancy.yml

# Git-fuzzy
- include_tasks: git-fuzzy.yml

# Gita
- include_tasks: gita.yml

# thefuck
- include_tasks: thefuck.yml

# BAT
- include_tasks: bat.yml

# Zoxide
- include_tasks: zoxide.yml

# Helm
- include_tasks: helm.yml

# ZSH
- include_tasks: zsh.yml

# Win32yank (windows clipboard support for Neovim)
- include_tasks: w32yank.yml
