---
# Common software
- include_tasks: packages.yml

# FZF (fuzzy-finder)
- include_tasks: fzf.yml

# Diff-so-fancy
- include_tasks: diff-so-fancy.yml

# Git-fuzzy
- include_tasks: git-fuzzy.yml

# thefuck
- include_tasks: thefuck.yml

# BAT
- include_tasks: bat.yml

# Zoxide
- include_tasks: zoxide.yml

# Helm
- include_tasks: helm.yml

# ZSH
- include_tasks: zsh.yml