---
# Ensure local bin/opt directories are there
- name: "[Software] Ensure dotted directories are there"
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - .local/bin
    - .local/opt
    - .config
    - .lsp

# Set software versions fact, will be updated in the tasks above, then printed at the end of play
- name: "[Software] Reset software versions fact"
  set_fact:
    used_software_versions: {}
    cacheable: true

# Common software
- include_tasks: packages.yml
  
# Latest GIT
- include_tasks: git.yml

# ripgrep
- include_tasks: ripgrep.yml

# FD
- include_tasks: fd.yml

# ls-with-git-status
- include_tasks: lsg.yml

# FZF (fuzzy-finder)
- include_tasks: fzf.yml

# Diff-so-fancy
- include_tasks: diff-so-fancy.yml

# Git-fuzzy
- include_tasks: git-fuzzy.yml

# LazyGIT
- include_tasks: lazygit.yml

# Gita
- include_tasks: gita.yml

# thefuck
- include_tasks: thefuck.yml

# BAT
- include_tasks: bat.yml

# Zoxide
- include_tasks: zoxide.yml

# Helm
- include_tasks: helm.yml

# ZSH
- include_tasks: zsh.yml

# Win32yank (windows clipboard support for Neovim)
- include_tasks: w32yank.yml

# TMUX Plugins
- include_tasks: tmux.yml
