---
# Ensure local bin/opt directories are there
- name: "[Software] Ensure dotted directories are there"
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - .local/bin
    - .local/opt
    - .config
    - .lsp

# Include override variables
- name: "[Software] Include vars/overrides.yml"
  include_vars: "{{ item }}"
  with_first_found: [ '../../../vars/overrides.yml' ]

# Set software versions fact, will be updated in the tasks above, then printed at the end of play
- name: "[Software] Reset software versions fact"
  set_fact:
    used_software_versions: {}
    cacheable: true

# Common software
- name: "[Software] Install packages"
  include_tasks: packages.yml
  when: "'packages' not in software_tasks_exclude"

# Latest GIT
- name: "[Software] Install git"
  include_tasks: git.yml
  when: "'git' not in software_tasks_exclude"

# ripgrep
- name: "[Software] Install ripgrep"
  include_tasks: ripgrep.yml
  when: "'ripgrep' not in software_tasks_exclude"

# FD
- name: "[Software] Install fd"
  include_tasks: fd.yml
  when: "'fd' not in software_tasks_exclude"

# ls-with-git-status
- name: "[Software] Install lsg"
  include_tasks: lsg.yml
  when: "'lsg' not in software_tasks_exclude"

# FZF (fuzzy-finder)
- name: "[Software] Install fzf"
  include_tasks: fzf.yml
  when: "'fzf' not in software_tasks_exclude"

# Diff-so-fancy
- name: "[Software] Install diff-so-fancy"
  include_tasks: diff-so-fancy.yml
  when: "'diff-so-fancy' not in software_tasks_exclude"

# Git-fuzzy
- name: "[Software] Install git-fuzzy"
  include_tasks: git-fuzzy.yml
  when: "'git-fuzzy' not in software_tasks_exclude"

# LazyGIT
- name: "[Software] Install lazygit"
  include_tasks: lazygit.yml
  when: "'lazygit' not in software_tasks_exclude"

# Gita
- name: "[Software] Install gita"
  include_tasks: gita.yml
  when: "'gita' not in software_tasks_exclude"

# thefuck
- name: "[Software] Install thefuck"
  include_tasks: thefuck.yml
  when: "'thefuck' not in software_tasks_exclude"

# BAT
- name: "[Software] Install bat"
  include_tasks: bat.yml
  when: "'bat' not in software_tasks_exclude"

# Zoxide
- name: "[Software] Install zoxide"
  include_tasks: zoxide.yml
  when: "'zoxide' not in software_tasks_exclude"

# Helm
- name: "[Software] Install helm"
  include_tasks: helm.yml
  when: "'helm' not in software_tasks_exclude"

# ZSH
- name: "[Software] Install zsh"
  include_tasks: zsh.yml
  when: "'zsh' not in software_tasks_exclude"

# Win32yank (windows clipboard support for Neovim)
- name: "[Software] Install w32yank"
  include_tasks: w32yank.yml
  when: "'w32yank' not in software_tasks_exclude"

# TMUX Plugins
- name: "[Software] Install tmux"
  include_tasks: tmux.yml
  when: "'tmux' not in software_tasks_exclude"
