# Install Neovim
# Source: https://github.com/neovim/neovim
---
- name: "[Neovim] Check installed Neovim version"
  ansible.builtin.command: dpkg-query -W neovim
  register: neovim_check_deb
  ignore_errors: true
  changed_when: neovim_check_deb.rc > 1
  failed_when: neovim_check_deb.rc > 1
  tags:
    - versions

- name: "[Neovim] Get Github URL for proper version"
  vars:
    app: neovim
    repo: neovim/neovim
    version_query: curl -s https://api.github.com/repos/neovim/neovim/releases/latest | grep -oP 'NVIM v([0-9]*\.[0-9]*\.[0-9])\\n' | grep -Eo '[0-9]*\.[0-9]*\.[0-9]'
    github_uri: "v{{ neovim_version }}/nvim-linux64.deb"
  ansible.builtin.include_role:
    name: common
    tasks_from: github_version.yml
  tags:
    - versions

- name: "Installation"
  when: neovim_check_deb.stdout | regex_search('[0-9]+\.[0-9]+\.[0-9]+') | default(0) != neovim_version
  block:
    - name: "[Neovim] Create directory in {{ ansible_env.HOME }}/.local/opt"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/opt/neovim-{{ neovim_version }}"
        state: directory
        mode: '0755'

    - name: "[Neovim] Download Neovim {{ neovim_version }}"
      ansible.builtin.get_url:
        url: "{{ neovim_url }}"
        dest: "{{ ansible_env.HOME }}/.local/opt/neovim-{{ neovim_version }}/nvim-{{ neovim_version }}-linux64.deb"
        mode: '0755'

    - name: "[Neovim] Install {{ neovim_version }} .deb package"
      ansible.builtin.apt:
        deb: "{{ ansible_env.HOME }}/.local/opt/neovim-{{ neovim_version }}/nvim-{{ neovim_version }}-linux64.deb"
      become: true

- name: "[Neovim] Save used version"
  vars:
    app: neovim
    target_version:
      neovim_version: "{{ neovim_version }}"
    query: ".neovim_version = \"{{ neovim_version }}\""
  ansible.builtin.include_role:
    name: common
    tasks_from: save_version.yml
  tags:
    - versions
