# SOme default packages installed from APT
---
- name: '[Packages] Install default packages'
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: 'present'
  loop: "{{ default_apt_packages }}"
