# RIPGREP (better, faster GREP)
# Source: https://github.com/BurntSushi/ripgrep
---
- name: "[Ripgrep] Check installed Ripgrep version"
  ansible.builtin.command: dpkg-query -W ripgrep
  register: ripgrep_check_deb
  ignore_errors: true
  changed_when: ripgrep_check_deb.rc > 1
  failed_when: ripgrep_check_deb.rc > 1

- name: "[Ripgrep] Get latest version if requested"
  ansible.builtin.shell: curl -s https://api.github.com/repos/BurntSushi/ripgrep/releases/latest | jq .name -r | cut -f2 -d'v'
  register: version
  changed_when: false
  ignore_errors: true
  when: versions['ripgrep'] == 'latest'

- name: "[Ripgrep] Set version to {{ version.stdout | default(versions['ripgrep']) }}"
  ansible.builtin.set_fact:
    ripgrep_version: "{{ version.stdout | default(versions['ripgrep']) }}"

- name: "[Ripgrep] Set proper download URL"
  ansible.builtin.set_fact:
    ripgrep_url: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}_amd64.deb"

- name: "Installation"
  when: ripgrep_check_deb.stdout | regex_search('[0-9]+\.[0-9]+\.[0-9]+') | default(0) != ripgrep_version
  block:
    - name: "[Ripgrep] Create directory in {{ ansible_env.HOME }}/.local/opt"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/opt/ripgrep-{{ ripgrep_version }}"
        state: directory
        mode: '0755'

    - name: "[Ripgrep] Download Ripgrep {{ ripgrep_version }}"
      ansible.builtin.get_url:
        url: "{{ ripgrep_url }}"
        dest: "{{ ansible_env.HOME }}/.local/opt/ripgrep-{{ ripgrep_version }}"
        mode: '0755'

    - name: "[Ripgrep] Install {{ ripgrep_version }} .deb package"
      ansible.builtin.apt:
        deb: "{{ ansible_env.HOME }}/.local/opt/ripgrep-{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}_amd64.deb"
      become: true

- name: "[Ripgrep] Save used version"
  ansible.builtin.set_fact:
    used_software_versions: "{{ used_software_versions | combine({'ripgrep': ripgrep_version}) }}"
