---
# TheFuck installation
# For usage see README.md
#
# Source: https://github.com/nvbn/thefuck
- name: "[TheFuck] Install TheFuck specific version"
  pip:
    name: "thefuck=={{ versions.thefuck }}"
    executable: pip3
  register: pip_out
  changed_when: "'Requirement already up-to-date' not in pip_out.stdout"
  when: versions['thefuck'] != 'latest'

- name: "[TheFuck] Install TheFuck latest version"
  pip:
    name: "thefuck"
    executable: pip3
    extra_args: --upgrade
  register: pip_out
  changed_when: "'Requirement already up-to-date' not in pip_out.stdout"
  when: versions['thefuck'] == 'latest'