---
# TheFuck installation
# For usage see README.md
#
# Source: https://github.com/nvbn/thefuck
- name: "[TheFuck] Install TheFuck specific version"
  ansible.builtin.pip:
    name: "thefuck=={{ versions.thefuck }}"
    executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip3"
  register: pip_out
  changed_when: "'Requirement already satisfied' not in pip_out.stdout"
  when: versions['thefuck'] != 'latest'

- name: "[TheFuck] Install TheFuck latest version"
  ansible.builtin.pip:
    name: "thefuck"
    executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip3"
    extra_args: --upgrade
  register: pip_out
  changed_when: "'Requirement already satisfied' not in pip_out.stdout"
  when: versions['thefuck'] == 'latest'

- name: "[TheFuck] Get installed TheFuck version"
  ansible.builtin.shell: |
    set -e -o pipefail
    pip3 show thefuck | grep Version | awk '{print $2}'
  changed_when: false
  args:
    executable: /bin/bash
  register: thefuck_version

- name: "[TheFuck] Save used version"
  ansible.builtin.set_fact:
    used_software_versions: "{{ used_software_versions | combine({'thefuck': thefuck_version.stdout}) }}"
