---
# TheFuck installation
# For usage see README.md
#
# Source: https://github.com/nvbn/thefuck
- name: "[TheFuck] Install TheFuck specific version"
  ansible.builtin.pip:
    name: "thefuck=={{ pip_packages['thefuck'] }}"
    executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip3"
  register: pip_out
  changed_when: "'Requirement already satisfied' not in pip_out.stdout"
  when: pip_packages['thefuck'] != 'latest'

- name: "[TheFuck] Install TheFuck latest version"
  ansible.builtin.pip:
    name: "thefuck"
    executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip3"
    extra_args: --upgrade
  register: pip_out
  changed_when: "'Requirement already satisfied' not in pip_out.stdout"
  when: pip_packages['thefuck'] == 'latest'

- name: "[TheFuck] Get installed TheFuck version"
  ansible.builtin.shell: |
    set -e -o pipefail
    {{ ansible_env.HOME }}/.pyenv/shims/pip3 show thefuck | grep Version | awk '{print $2}'
  changed_when: false
  args:
    executable: /bin/bash
  register: thefuck_version
  tags:
    - versions

- name: "[Thefuck] Save used version"
  vars:
    app: thefuck
    target_version:
      pip_packages:
        thefuck: "{{ thefuck_version.stdout }}"
    query: ".pip_packages.thefuck = \"{{ thefuck_version.stdout }}\""
  ansible.builtin.import_role:
    name: common
    tasks_from: save_version.yml
  tags:
    - versions
