# TMUX plugin manager
# Source: https://github.com/tmux-plugins/tpm
---
- name: "[Tmux] Get latest version if requested"
  ansible.builtin.shell: curl -s https://api.github.com/repos/tmux/tmux/releases/latest | jq .name -r | cut -f2 -d'v' | awk '{ print $2 }'
  register: version
  changed_when: false
  ignore_errors: true
  when: github_packages['tmux'] == 'latest'

- name: "[Tmux] Set version to {{ version.stdout | default(github_packages['tmux']) }}"
  ansible.builtin.set_fact:
    tmux_version: "{{ version.stdout | default(github_packages['tmux']) }}"

- name: "[Tmux] Set proper download URL"
  ansible.builtin.set_fact:
    tmux_url: "https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz"

- name: "[Tmux] Check if Tmux {{ tmux_version }} is installed"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/opt/tmux-{{ tmux_version }}"
  register: tmux_dir

- name: "Installation"
  when: not tmux_dir.stat.exists
  block:
    - name: "[Tmux] Download Tmux {{ tmux_version }}"
      ansible.builtin.get_url:
        url: "{{ tmux_url }}"
        dest: "/tmp/tmux-{{ tmux_version }}.tar.gz"
        mode: '0755'

    - name: "[Tmux] Create directory in {{ ansible_env.HOME }}/.local/opt"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/opt/tmux-{{ tmux_version }}"
        state: directory
        mode: '0755'

    - name: "[Tmux] Turn on failed installation handler"
      ansible.builtin.set_fact:
        tmux_failed: true

    - name: "[Tmux] Untar archive"
      ansible.builtin.unarchive:
        src: "/tmp/tmux-{{ tmux_version }}.tar.gz"
        dest: "{{ ansible_env.HOME }}/.local/opt"

    - name: "[Tmux] Configure & make"
      ansible.builtin.shell: "./configure && make"
      args:
        chdir: "{{ ansible_env.HOME }}/.local/opt/tmux-{{ tmux_version }}"

    - name: "[Tmux] Make install"
      ansible.builtin.command: "make install"
      args:
        chdir: "{{ ansible_env.HOME }}/.local/opt/tmux-{{ tmux_version }}"
      become: true

    - name: "[Tmux] Turn off failed installation handler"
      ansible.builtin.set_fact:
        tmux_failed: false

    - name: "[Tmux] Cleanup tar.gz file"
      ansible.builtin.file:
        path: "/tmp/tmux-{{ tmux_version }}.tar.gz"
        state: absent

    - name: "[TMUX] Create Tmux plugin dir {{ ansible_env.HOME }}/.tmux/plugins"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.tmux/plugins"
        state: directory
        mode: 0755
        recurse: true

    - name: "[TMUX] Clone/update Tmux plugin manager"
      ansible.builtin.git:
        repo: "{{ tpm_git_url }}"
        dest: "{{ tmux_plugins_dir }}/tpm"
        force: true
        update: true
  rescue:
    - name: "[Tmux] Remove TMUX dir {{ ansible_env.HOME }}/.local/opt/tmux-{{ tmux_version }} as installation failed"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/opt/tmux-{{ tmux_version }}"
        state: absent
      when: tmux_failed | bool

    - name: "[Tmux] Fail run if TMUX installation failed"
      ansible.builtin.fail:
        msg: '[Tmux] There was an error during Tmux installation, failing build... See output above for more details.'
      when: tmux_failed | bool

- name: "[Tmux] Save used version"
  ansible.builtin.set_fact:
    used_software_versions: "{{ used_software_versions | combine({'tmux': tmux_version}) }}"
