# Installs:
#  - ZSH shell
#  - oh-my-zsh plugin (https://ohmyz.sh/ | https://github.com/ohmyzsh/ohmyzsh/)
#  - Powerlevel10k theme 
#  - custom plugins (see README.md for full list and usages)
---
- name: '[Zsh] Install Zsh and friends'
  become: True
  become_user: root
  package: name={{ item }}
  with_items:
    - git-core
    - powerline
    - zsh

- name: '[Zsh] Check current default shell'
  become: True
  become_user: root
  command: sh -c "grep {{ user }} /etc/passwd | grep -o '[^:]*$'"
  register: user_shell
  changed_when: user_shell.rc < 0

- name: '[Zsh] Update shell to Zsh'
  become: True
  become_user: root
  command: chsh -s /bin/zsh {{ user }}
  when: user_shell.stdout != '/bin/zsh'

- name: '[Zsh] Check for Oh-My-Zsh'
  stat: path=$HOME/.oh-my-zsh
  register: ohmyzsh

- name: '[Zsh] Install Oh-My-Zsh'
  shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
  when: not ohmyzsh.stat.exists

- name: "[Zsh] Plugins install/update"
  git:
    repo: "{{ item.value }}"
    dest: "{{ omz_home }}/custom/plugins/{{ item.key }}"
    update: yes
  loop: "{{ omz_plugins | dict2items }}"

- name: '[Zsh] Check for powerlevel10k theme'
  stat: path="{{ omz_home }}/custom/themes/powerlevel10k"
  register: powerlevel10k

- name: '[Zsh] Clone powerlevel10k'
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ omz_home }}/custom/themes/powerlevel10k
  when: not powerlevel10k.stat.exists