# Installs:
#  - ZSH shell
#  - oh-my-zsh plugin (https://ohmyz.sh/ | https://github.com/ohmyzsh/ohmyzsh/)
#  - Powerlevel10k theme
#  - custom plugins (see README.md for full list and usages)
---
- name: '[Zsh] Install Zsh and friends'
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - git-core
    - powerline
    - zsh

- name: '[Zsh] Check current default shell'
  become: true
  become_user: root
  ansible.builtin.command: sh -c "grep {{ ansible_user_id }} /etc/passwd | grep -o '[^:]*$'"
  register: user_shell
  changed_when: user_shell.rc < 0

- name: '[Zsh] Update shell to Zsh'
  become: true
  become_user: root
  ansible.builtin.command: chsh -s /bin/zsh {{ ansible_user_id }}
  when: user_shell.stdout != '/bin/zsh'

- name: '[Zsh] Check for Oh-My-Zsh'
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh
  register: ohmyzsh

- name: '[Zsh] Install Oh-My-Zsh'
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
  when: not ohmyzsh.stat.exists

- name: "[Zsh] Plugins install/update"
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: "{{ omz_home }}/custom/plugins/{{ item.key }}"
    update: true
  loop: "{{ omz_plugins | dict2items }}"

- name: '[Zsh] Check for powerlevel10k theme'
  ansible.builtin.stat:
    path: "{{ omz_home }}/custom/themes/powerlevel10k"
  register: powerlevel10k

- name: '[Zsh] Clone powerlevel10k'
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ omz_home }}/custom/themes/powerlevel10k"
    depth: 1
  when: not powerlevel10k.stat.exists
