---
# Specific versions for software (github)
# Fixed versions should be set without `v` prefix (e.g: 1.4.3)
versions:
  diff-so-fancy: latest 
  bat: latest
  zoxide: latest
  helm: latest
  thefuck: latest
  gita: latest
  lazygit: latest
  fzf: latest
  git-fuzzy: latest
  tmux: latest
  ripgrep: latest
  fd: latest

# Useful packages (apt)
packages:
  - git
  - curl
  - unzip
  - mlocate
  - libevent-dev # Required for latest Tmux install
  - tree
  - htop
  - jq
  - gcc
  - zip
  - ctags
  - dos2unix
  - php
  - composer
  - groff # AWS cli req

# FZF
fzf_git_url: "https://github.com/junegunn/fzf.git"
fzf_home: "{{ ansible_env.HOME }}/.fzf"

# GIT Fuzzy
git_fuzzy_url: "https://github.com/bigH/git-fuzzy.git"
git_fuzzy_home: "{{ ansible_env.HOME }}/.local/opt/git-fuzzy"
git_fuzzy_branch: "master"

# Oh-My-Zsh
omz_home: "{{ ansible_env.HOME }}/.oh-my-zsh"
omz_plugins:
  fzf-tab: https://github.com/Aloxaf/fzf-tab
  k: https://github.com/supercrabtree/k
  you-should-use: https://github.com/MichaelAquilina/zsh-you-should-use.git
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting.git
  zsh-sdkman: https://github.com/matthieusb/zsh-sdkman.git

# TMUX Plugin Manager
tpm_git_url: https://github.com/tmux-plugins/tpm.git
tmux_plugins_dir: "{{ ansible_env.HOME }}/.tmux/plugins"