---
# Add this variable to your ansible/vars/overrides.yml if needed
# This is array of tasks to exclude from software role.
# For list of tasks see: software/tasks/main.yml or see README.md
software_tasks_exclude: []

# System manager to use. Ansible has issues detecting SysV vs. SystemD on WSL distributions
# If you are using SysVInit WSL (not recommended, see `README.md`), overwrite this in `ansible/vars/overrides.yml` to `sysvinit`
service_manager: systemd

# Default packages to be installed first, using APT
# There is no version here as those are Ubuntu distro defaults always
default_apt_packages:
  - curl
  - unzip
  - mlocate
  - tree
  - htop
  - jq
  - gcc
  - zip
  - dos2unix
  - php
  - composer
  - keychain
  - groff # Required for AWS CLI
  - libevent-dev # v Required for latest Tmux install
  - universal-ctags # v Required for latest Tmux install
  - ncurses-dev # v Required for latest Tmux install

# Specific versions for software (github)
# Fixed versions should be set without `v` prefix (e.g: 1.4.3)
github_packages:
  diff_so_fancy: latest
  bat: latest
  zoxide: latest
  helm: latest
  git: latest
  lazygit: latest
  fzf: latest
  tmux: latest
  ripgrep: latest
  fd: latest
  kind: latest
  k9s: latest
  yq: latest
  win32yank: latest

# Kubectl version
kubectl_version: latest

# Packages and their versions to install with PIP
pip_packages:
  thefuck: latest
  gita: latest

# FZF
fzf_git_url: "https://github.com/junegunn/fzf.git"
fzf_home: "{{ ansible_env.HOME }}/.fzf"

# Git from custom PPA repo
git_apt_version: latest

# GIT Fuzzy
git_fuzzy_url: "https://github.com/bigH/git-fuzzy.git"
git_fuzzy_home: "{{ ansible_env.HOME }}/.local/opt/git-fuzzy"
git_fuzzy_version: "master" # Branch name or commit - git-fuzzy does not have releases

# Oh-My-Zsh
omz_home: "{{ ansible_env.HOME }}/.oh-my-zsh"
omz_plugins:
  fzf-tab: https://github.com/Aloxaf/fzf-tab
  k: https://github.com/supercrabtree/k
  you-should-use: https://github.com/MichaelAquilina/zsh-you-should-use.git
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting.git
  zsh-sdkman: https://github.com/matthieusb/zsh-sdkman.git
  zsh-lazyload: https://github.com/qoomon/zsh-lazyload
  pyenv-lazy: https://github.com/davidparsson/zsh-pyenv-lazy.git
  zsh-snv: https://github.com/rpeshkov/zsh-snv

# P10k version
p10k_version: master

# TMUX Plugin Manager
tmux_plugins_dir: "{{ ansible_env.HOME }}/.tmux/plugins"
tpm_git_url: https://github.com/tmux-plugins/tpm.git
tpm_version: master

# Docker system dependency packages
docker_apt_dependencies:
  - ca-certificates
  - gnupg
  - lsb-release

# Docker main packages from APT repo
docker_apt_packages:
  docker-ce: latest
  docker-ce-cli: latest
  containerd.io: latest
  docker-compose-plugin: latest
