---
# Add this variable to your ansible/vars/overrides.yml if needed
# This is array of tasks to exclude from software role.
# For list of tasks see: software/tasks/main.yml or see README.md
software_tasks_exclude: []

# System manager to use. Ansible has issues detecting SysV vs. SystemD on WSL distributions
# If you are using SysVInit WSL (not recommended, see `README.md`), overwrite this in `ansible/vars/overrides.yml` to `sysvinit`
service_manager: systemd

# Default packages to be installed first, using APT
default_apt_packages:
  curl: latest
  unzip: latest
  mlocate: latest
  # v Required for latest Tmux install
  libevent-dev: latest
  tree: latest
  htop: latest
  jq: latest
  gcc: latest
  zip: latest
  # v Required for latest Tmux install
  universal-ctags: latest
  # v Required for latest Tmux install
  ncurses-dev: latest
  dos2unix: latest
  php: latest
  composer: latest
  # v Required for latest Tmux install
  groff: latest
  keychain: latest

# Specific versions for software (github)
# Fixed versions should be set without `v` prefix (e.g: 1.4.3)
github_packages:
  diff-so-fancy: latest
  bat: latest
  zoxide: latest
  helm: latest
  git: latest
  lazygit: latest
  fzf: latest
  git-fuzzy: latest
  tmux: latest
  ripgrep: latest
  fd: latest
  kubectl: latest # TODO: this is not github
  kind: latest
  k9s: latest
  yq: latest

# Packages and their versions to install with PIP
pip_packages:
  thefuck: latest
  gita: latest

# FZF
fzf_git_url: "https://github.com/junegunn/fzf.git"
fzf_home: "{{ ansible_env.HOME }}/.fzf"

# Git from custom PPA repo
git_apt_version: latest

# GIT Fuzzy
git_fuzzy_url: "https://github.com/bigH/git-fuzzy.git"
git_fuzzy_home: "{{ ansible_env.HOME }}/.local/opt/git-fuzzy"
# v Can be tag, or branch name
git_fuzzy_version: "master"

# Oh-My-Zsh
omz_home: "{{ ansible_env.HOME }}/.oh-my-zsh"
omz_plugins:
  fzf-tab: https://github.com/Aloxaf/fzf-tab
  k: https://github.com/supercrabtree/k
  you-should-use: https://github.com/MichaelAquilina/zsh-you-should-use.git
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting.git
  zsh-sdkman: https://github.com/matthieusb/zsh-sdkman.git
  zsh-lazyload: https://github.com/qoomon/zsh-lazyload
  pyenv-lazy: https://github.com/davidparsson/zsh-pyenv-lazy.git
  zsh-snv: https://github.com/rpeshkov/zsh-snv

# TMUX Plugin Manager
tmux_plugins_dir: "{{ ansible_env.HOME }}/.tmux/plugins"
tpm_git_url: https://github.com/tmux-plugins/tpm.git
tpm_version: master

# Docker dependency packages
docker_apt_dependencies:
  ca-certificates: latest
  gnupg: latest
  lsb-release: latest

# Docker main packages
docker_apt_packages:
  docker-ce: latest
  docker-ce-cli: latest
  containerd.io: latest
  docker-compose-plugin: latest
