---
# Add this variable to your ansible/vars/overrides.yml if needed
# This is array of tasks to exclude from software role.
# For list of tasks see: software/tasks/main.yml or see README.md
software_tasks_exclude: []

# System manager to use. Ansible has issues detecting SysV vs. SystemD on WSL distributions
# If you are using systemd WSL, overwrite this in `ansible/vars/overrides.yml` to `systemd`
service_manager: sysvinit

# Specific versions for software (github)
# Fixed versions should be set without `v` prefix (e.g: 1.4.3)
versions:
  diff-so-fancy: latest
  bat: latest
  zoxide: latest
  helm: latest
  thefuck: latest
  git: latest
  gita: latest
  lazygit: latest
  fzf: latest
  git-fuzzy: latest
  tmux: latest
  ripgrep: latest
  fd: latest
  kubectl: latest
  kind: latest
  k9s: latest

# Useful packages (apt)
packages:
  git: latest
  curl: latest
  unzip: latest
  mlocate: latest
  libevent-dev: latest    # Required for latest Tmux install
  tree: latest
  htop: latest
  jq: latest
  gcc: latest
  zip: latest
  universal-ctags: latest # Required for latest Tmux install
  ncurses-dev: latest     # Required for latest Tmux install
  dos2unix: latest
  php: latest
  composer: latest
  groff: latest           # AWS cli req
  keychain: latest

# Docker dependency packages
docker_dependencies:
  ca-certificates: latest
  gnupg: latest
  lsb-release: latest

docker_packages:
  docker-ce: latest
  docker-ce-cli: latest
  containerd.io: latest
  docker-compose-plugin: latest

# FZF
fzf_git_url: "https://github.com/junegunn/fzf.git"
fzf_home: "{{ ansible_env.HOME }}/.fzf"

# GIT Fuzzy
git_fuzzy_url: "https://github.com/bigH/git-fuzzy.git"
git_fuzzy_home: "{{ ansible_env.HOME }}/.local/opt/git-fuzzy"
git_fuzzy_branch: "master"

# Oh-My-Zsh
omz_home: "{{ ansible_env.HOME }}/.oh-my-zsh"
omz_plugins:
  fzf-tab: https://github.com/Aloxaf/fzf-tab
  k: https://github.com/supercrabtree/k
  you-should-use: https://github.com/MichaelAquilina/zsh-you-should-use.git
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting.git
  zsh-sdkman: https://github.com/matthieusb/zsh-sdkman.git

# TMUX Plugin Manager
tpm_git_url: https://github.com/tmux-plugins/tpm.git
tmux_plugins_dir: "{{ ansible_env.HOME }}/.tmux/plugins"
