---
# Add this variable to your ansible/vars/overrides.yml if needed
# This is array of tasks to exclude from software role.
# For list of tasks see: software/tasks/main.yml or see README.md
software_tasks_exclude: []

# System manager to use. Ansible has issues detecting SysV vs. SystemD on WSL distributions
# If you are using SysVInit WSL (not recommended, see `README.md`), overwrite this in `ansible/vars/overrides.yml` to `sysvinit`
service_manager: systemd

# FZF
fzf_git_url: "https://github.com/junegunn/fzf.git"
fzf_home: "{{ ansible_env.HOME }}/.fzf"

# GIT Fuzzy
git_fuzzy_url: "https://github.com/bigH/git-fuzzy.git"
git_fuzzy_home: "{{ ansible_env.HOME }}/.local/opt/git-fuzzy"

# Oh-My-Zsh
omz_home: "{{ ansible_env.HOME }}/.oh-my-zsh"
omz_plugins:
  fzf-tab: https://github.com/Aloxaf/fzf-tab
  k: https://github.com/supercrabtree/k
  you-should-use: https://github.com/MichaelAquilina/zsh-you-should-use.git
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting.git
  zsh-sdkman: https://github.com/matthieusb/zsh-sdkman.git
  zsh-lazyload: https://github.com/qoomon/zsh-lazyload
  pyenv-lazy: https://github.com/davidparsson/zsh-pyenv-lazy.git
  zsh-snv: https://github.com/rpeshkov/zsh-snv

# TMUX Plugin Manager
tpm_git_url: https://github.com/tmux-plugins/tpm.git
tmux_plugins_dir: "{{ ansible_env.HOME }}/.tmux/plugins"
