---
# Specific versions for software (github)
# Fixed versions should be set without `v` prefix (e.g: 1.4.3)
github_packages:
  diff-so-fancy: latest
  bat: latest
  zoxide: latest
  helm: latest
  git: latest
  lazygit: latest
  fzf: latest
  git-fuzzy: latest
  tmux: latest
  ripgrep: latest
  fd: latest
  kubectl: latest # TODO: this is not github
  kind: latest
  k9s: latest

pip_packages:
  thefuck: latest
  gita: latest

# Useful packages (apt)
default_apt_packages:
  curl: latest
  unzip: latest
  mlocate: latest
  libevent-dev: latest    # Required for latest Tmux install
  tree: latest
  htop: latest
  jq: latest
  gcc: latest
  zip: latest
  universal-ctags: latest # Required for latest Tmux install
  ncurses-dev: latest     # Required for latest Tmux install
  dos2unix: latest
  php: latest
  composer: latest
  groff: latest           # AWS cli req
  keychain: latest

# Git from custom PPA repo
git_apt_version: latest

# Git Fuzzy
git_fuzzy_version: "master"

# Docker dependency packages
docker_apt_dependencies:
  ca-certificates: latest
  gnupg: latest
  lsb-release: latest

# Docker main packages
docker_apt_packages:
  docker-ce: latest
  docker-ce-cli: latest
  containerd.io: latest
  docker-compose-plugin: latest
