- name: WSL Ubuntu Power Environment
  hosts: ubuntu
  ### Comment out roles you don't need ###
  vars:
    summary: |
            #################################################################################

            Thank you for using
               ___                              _
              / _ \_ __ _____   _____  __ _ ___(_) ___
             / /_)/ '__/ _ \ \ / / _ \/ _` / __| |/ _ \
            / ___/| | | (_) \ V /  __/ (_| \__ \ | (_) |
            \/    |_|  \___/ \_/ \___|\__,_|___/_|\___/

            For configuration, example usage and customization options, please see Usages.md.

            #################################################################################

            This ansible run ended up with below versions installed/upgraded:

            TODO: versions

            All above versions are added to `./current-versions.yml`
            If you want to use those versions for subsequent runs, put those in `./vars/overrides.yml`. See README.md for details.
  tasks:
    - name: '[Init] Check sudo password'
      ansible.builtin.command: echo "sudo password is correct"
      become: true
      changed_when: false
      tags:
        - always
    - name: '[Software] Include software role'
      ansible.builtin.import_role:
        name: software
    - name: '[Dev] Include dev role'
      ansible.builtin.import_role:
        name: dev
    - name: '[Config] Include config role'
      ansible.builtin.import_role:
        name: config
    - name: "[Summary] Show detailed info"
      ansible.builtin.debug:
        var: summary
      tags:
        - always

    # - name: "[Summary] Save all versions in current-versions.yaml"
    #   ansible.builtin.template:
    #     src: 'templates/current-versions.j2'
    #     dest: 'current-versions.yaml'
    #     mode: '0644'
