- hosts: wsl
  vars_files:
    - vars/environment.yml
  ### Comment out roles you don't need ###
  roles:
    - software
    - config
    - dev
  ### Set this in vars/environment! ###
  user: "{{ user }}"