---
- name: Install common usage applications
  win_chocolatey:
    name: "{{ package }}"
    install_args: "--install-directory {{ target_installation_drives['common'] }}\\{{ install_dir_names[package] }}"
    state: latest
    loop:
      - 7zip
      - notepadplusplus
      - firefox
      - thunderbird
      - bitwarden
      - boxcryptor
      - naps2
      - todoist
      - openvpn
      - veracrypt
      - tor-browser
    loop_control:
      loop_var: package