---
- name: Install common usage applications
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ package }}"
    state: latest
  loop:
    - 7zip
    - notepadplusplus
    - firefox
    - thunderbird
    - bitwarden
    - boxcryptor
    - naps2
    - todoist
    - openvpn
    - veracrypt
    - tor-browser
  loop_control:
    loop_var: package
