# Cleanup some context menu items not to show up.
---
# VLC
- name: Remove VLC context menu item (Add to playlist)
  ansible.windows.win_regedit:
    path: HKCR:\Directory\shell\AddToPlaylistVLC
    state: absent

- name: Remove VLC context menu item (Play with VLC)
  ansible.windows.win_regedit:
    path: HKCR:\Directory\shell\PlayWithVLC
    state: absent

# Git
- name: Remove git gui context menu item (background)
  ansible.windows.win_regedit:
    path: HKCR:\Directory\Background\shell\git_gui
    state: absent

- name: Remove git bash context menu item (background)
  ansible.windows.win_regedit:
    path: HKCR:\Directory\Background\shell\git_shell
    state: absent

- name: Remove git gui context menu item
  ansible.windows.win_regedit:
    path: HKCR:\Directory\shell\git_gui
    state: absent

- name: Remove git bash context menu item
  ansible.windows.win_regedit:
    path: HKCR:\Directory\shell\git_shell
    state: absent
