---
- name: Install GIT
  win_chocolatey:
    name: git
    state: latest

- name: Install VSCode + IntelliJ IDEA
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  loop:
    - vscode
    - intellijidea-community
    
- name: Install Windows Terminal
  win_chocolatey:
    name: microsoft-windows-terminal
    state: latest

- name: Install Chocolatey GUI
  win_chocolatey:
    name: chocolateygui
    state: latest

- name: Install Docker Desktop
  win_chocolatey:
    name: docker-desktop
    state: latest

- name: Install Postman
  win_chocolatey:
    name: postman
    state: latest
