---
- name: Install GIT
  chocolatey.chocolatey.win_chocolatey:
    name: git
    state: latest

- name: Install VSCode + IntelliJ IDEA
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: latest
  loop:
    - vscode
    - intellijidea-community

- name: Install Windows Terminal
  chocolatey.chocolatey.win_chocolatey:
    name: microsoft-windows-terminal
    state: latest

- name: Install Chocolatey GUI
  chocolatey.chocolatey.win_chocolatey:
    name: chocolateygui
    state: latest

- name: Install Docker Desktop
  chocolatey.chocolatey.win_chocolatey:
    name: docker-desktop
    state: latest

- name: Install Postman
  chocolatey.chocolatey.win_chocolatey:
    name: postman
    state: latest
