---
- name: Install entertainment applications
  win_chocolatey:
    name: "{{ package }}"
    state: latest
  loop:
    - vlc
    - spotify
    - foobar2000
    - discord
    - steam-client
  loop_control:
    loop_var: package