---
- name: "Copy MesloLGS fonts"
  win_copy:
    src: "fonts/{{ item }}"
    dest: "%SYSTEMROOT%\\fonts\\{{ item }}"
  loop:
    - 'MesloLGS NF Regular.ttf'
    - 'MesloLGS NF Bold.ttf'
    - 'MesloLGS NF Italic.ttf'
    - 'MesloLGS NF Bold Italic.ttf'

- name: "Create registry entries"
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts"
    name: "{{ item }}"
    data: "{{ item }}"
  loop:
    - 'MesloLGS NF Regular.ttf'
    - 'MesloLGS NF Bold.ttf'
    - 'MesloLGS NF Italic.ttf'
    - 'MesloLGS NF Bold Italic.ttf'

## Windows Terminal Options
- name: Copy Windows Terminal settings.json
  win_template:
    src: "settings.json.j2"
    dest: "{{ ansible_env.LOCALAPPDATA }}\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json"
