---
- name: "Copy FiraCode fonts"
  ansible.windows.win_copy:
    src: "fonts/{{ item }}"
    dest: "%SYSTEMROOT%\\fonts\\{{ item }}"
  loop:
    - 'FiraCodeNerdFont-Bold.ttf'
    - 'FiraCodeNerdFont-Light.ttf'
    - 'FiraCodeNerdFont-Medium.ttf'
    - 'FiraCodeNerdFont-Regular.ttf'

- name: "Create registry entries"
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts"
    name: "{{ item }}"
    data: "{{ item }}"
  loop:
    - 'FiraCodeNerdFont-Bold.ttf'
    - 'FiraCodeNerdFont-Light.ttf'
    - 'FiraCodeNerdFont-Medium.ttf'
    - 'FiraCodeNerdFont-Regular.ttf'

## Windows Terminal Options
- name: Copy Windows Terminal settings.json
  ansible.windows.win_template:
    src: "settings.json.j2"
    dest: "{{ ansible_env.LOCALAPPDATA }}\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json"
