---
- name: "Copy MesloLGS fonts"
  win_copy:
    src: "fonts/{{ item }}"
    dest: "%SYSTEMROOT%\\fonts\\{{ item }}"
  loop:
    - 'MesloLGS NF Regular.ttf'
    - 'MesloLGS NF Bold.ttf'
    - 'MesloLGS NF Italic.ttf'
    - 'MesloLGS NF Bold Italic.ttf'

- name: "Create registry entries"
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts"
    name: "{{ item }}"
    data: "{{ item }}"
  loop:
    - 'MesloLGS NF Regular.ttf'
    - 'MesloLGS NF Bold.ttf'
    - 'MesloLGS NF Italic.ttf'
    - 'MesloLGS NF Bold Italic.ttf'

## Windows Terminal Options
- name: "Find Windows Terminal AppData Directory"
  register: terminal_appdata
  win_find:
    paths: "{{ ansible_env.LOCALAPPDATA }}\\Packages"
    patterns: "Microsoft.WindowsTerminal_*"
    file_type: "directory"

- name: Copy Windows Terminal settings.json
  win_template:
    src: "settings.json.j2"
    dest: "{{ terminal_appdata.files[0].path }}\\LocalState\\settings.json"