name: WSL/Ubuntu build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Prepare for setup
        run: sudo sh prepare-wsl.sh

      - name: Setup environment
        working-directory: ./ansible
        run: ansible-playbook -i inventory.yml setup-wsl.yaml

  ubuntu-20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Prepare for setup
        run: sudo sh prepare-wsl.sh

      - name: Setup environment
        working-directory: ./ansible
        run: ansible-playbook -i inventory.yml setup-wsl.yaml
