name: "pre-release"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Fix grub-efi-amd64 error
        run: |
          sudo apt remove shim-signed grub-efi-amd64-bin -y --allow-remove-essential

      - name: Prepare for setup
        run: sudo sh prepare-ubuntu.sh

      - name: Setup environment
        working-directory: ./ansible
        run: ansible-playbook -i inventory.yml setup-ubuntu.yml

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Pre-release Build"
